# Generated by Django 4.2.4 on 2023-10-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aziende",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                ("p_iva", models.IntegerField(null=True)),
                ("cod_fis", models.TextField(max_length=200, null=True)),
                (
                    "voto",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")], max_length=2, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aziende",
            },
        ),
        migrations.CreateModel(
            name="Commessa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                (
                    "tipologia",
                    models.CharField(
                        choices=[("CO", "Commerciale"), ("FO", "Formazione 4.0"), ("PR", "Procacciamento")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("ultimo_aggiornamento", models.DateField(blank=True, null=True)),
                (
                    "priorità",
                    models.CharField(
                        choices=[("BA", "Bassa"), ("MD", "Media"), ("AL", "Alta")], max_length=2, null=True
                    ),
                ),
                (
                    "id_aziende",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.aziende"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Commessa",
            },
        ),
        migrations.CreateModel(
            name="Contatti",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                ("in_qualita_di", models.CharField(max_length=200, null=True)),
                ("commesse", models.ManyToManyField(to="neapolitanmods.commessa")),
                (
                    "legale_rappresentante",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.aziende"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contatti",
            },
        ),
        migrations.CreateModel(
            name="Contratti",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                ("ultimo_aggiornamento", models.DateField(blank=True, null=True)),
                ("data_creazione", models.DateField(blank=True, null=True)),
                (
                    "id_commessa",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.commessa"
                    ),
                ),
                (
                    "sog_attivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratti_attivi",
                        to="neapolitanmods.aziende",
                    ),
                ),
                (
                    "sog_passivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratti_passivi",
                        to="neapolitanmods.aziende",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contratti",
            },
        ),
        migrations.CreateModel(
            name="Utente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("telefono", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name_plural": "Utente",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DE", "Da definire"), ("TA", "task"), ("CO", "Consegna")], max_length=2, null=True
                    ),
                ),
                ("data_creazione", models.DateField(blank=True, null=True)),
                ("sollecito", models.DateField(blank=True, null=True)),
                (
                    "priorità",
                    models.CharField(
                        choices=[("BA", "Bassa"), ("MD", "Medio"), ("AL", "Alta")], max_length=2, null=True
                    ),
                ),
                (
                    "id_commessa",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.commessa"
                    ),
                ),
                (
                    "id_contatti",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.contatti"
                    ),
                ),
                (
                    "responsabile",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.utente"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task",
            },
        ),
        migrations.CreateModel(
            name="Servizio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                (
                    "tipologia",
                    models.CharField(
                        choices=[("CO", "Commerciale"), ("FO", "Formazione 4.0"), ("PR", "Procacciamento")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("link_fonte", models.TextField(max_length=200, null=True)),
                ("documenti", models.FileField(null=True, upload_to="")),
                ("scheda_clienti", models.FileField(null=True, upload_to="")),
                (
                    "referente",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.utente"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Servizio",
            },
        ),
        migrations.CreateModel(
            name="Fatture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "anno_competenza",
                    models.CharField(
                        choices=[("20", "2020"), ("21", "2021"), ("22", "2022"), ("23", "2023")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("nome", models.CharField(max_length=200, null=True)),
                ("id_monday", models.IntegerField(null=True)),
                ("data_incasso", models.DateField(blank=True, null=True)),
                ("importo", models.FloatField(null=True)),
                (
                    "commessa",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.commessa"
                    ),
                ),
                (
                    "contratto",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.contratti"
                    ),
                ),
                (
                    "parte_passiva",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.aziende"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fatture",
            },
        ),
        migrations.AddField(
            model_name="commessa",
            name="id_servizio",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.task"),
        ),
        migrations.AddField(
            model_name="aziende",
            name="commesse",
            field=models.ManyToManyField(to="neapolitanmods.commessa"),
        ),
        migrations.AddField(
            model_name="aziende",
            name="id_contatti",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.contatti"
            ),
        ),
        migrations.AddField(
            model_name="aziende",
            name="responsabile",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.utente"
            ),
        ),
    ]
