# Generated by Django 4.2.4 on 2023-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commessa",
            name="id_monday",
            field=models.BigIntegerField(null=True),
        ),
    ]
