# Generated by Django 4.2.4 on 2023-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0002_alter_commessa_id_monday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commessa",
            name="tipologia",
            field=models.CharField(
                choices=[("CO", "Commerciale"), ("FO", "Formazione 4.0"), ("PR", "Procacciamento")],
                max_length=20,
                null=True,
            ),
        ),
    ]
