# Generated by Django 4.2.4 on 2023-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0004_alter_commessa_tipologia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commessa",
            name="priorità",
            field=models.CharField(
                choices=[("BA", "Bassa"), ("MD", "Media"), ("AL", "Alta")], max_length=200, null=True
            ),
        ),
    ]
