# Generated by Django 4.2.4 on 2023-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0007_alter_aziende_id_monday"),
    ]

    operations = [
        migrations.AddField(
            model_name="commessa",
            name="id_azienda",
            field=models.BigIntegerField(null=True),
        ),
    ]
