# Generated by Django 4.2.4 on 2023-10-06 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0008_commessa_id_azienda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commessa",
            name="id_azienda",
        ),
    ]
