# Generated by Django 4.2.4 on 2023-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0010_alter_commessa_id_monday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commessa",
            name="id_monday",
            field=models.BigIntegerField(null=True),
        ),
    ]
