# Generated by Django 4.2.4 on 2023-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0011_alter_commessa_id_monday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aziende",
            name="p_iva",
            field=models.BigIntegerField(null=True),
        ),
    ]
