# Generated by Django 4.2.4 on 2023-10-09 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0012_alter_aziende_p_iva"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aziende",
            name="id_contatti",
        ),
    ]
