# Generated by Django 4.2.4 on 2023-10-09 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0013_remove_aziende_id_contatti"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commessa",
            old_name="id_aziende",
            new_name="cliente_finale",
        ),
        migrations.RemoveField(
            model_name="aziende",
            name="voto",
        ),
    ]
