# Generated by Django 4.2.4 on 2023-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0014_rename_id_aziende_commessa_cliente_finale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commessa",
            name="priorità",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
