# Generated by Django 4.2.4 on 2023-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0016_alter_contatti_id_monday_alter_contratti_id_monday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aziende",
            name="id_commessa",
            field=models.BigIntegerField(null=True),
        ),
    ]
