# Generated by Django 4.2.4 on 2023-10-10 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0018_commessa_id_azienda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servizio",
            name="scheda_clienti",
        ),
    ]
