# Generated by Django 4.2.4 on 2023-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0019_remove_servizio_scheda_clienti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priorità",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="tipo",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
