# Generated by Django 4.2.4 on 2023-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0020_alter_task_priorità_alter_task_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="commesse",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="neapolitanmods.commessa"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id_commessa",
            field=models.BigIntegerField(null=True),
        ),
    ]
