# Generated by Django 4.2.4 on 2023-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0021_task_commesse_alter_task_id_commessa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="commesse",
        ),
        migrations.AddField(
            model_name="task",
            name="commesse",
            field=models.ManyToManyField(to="neapolitanmods.commessa"),
        ),
    ]
