# Generated by Django 4.2.4 on 2023-10-11 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0022_remove_task_commesse_task_commesse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="id_contatti",
        ),
    ]
