# Generated by Django 4.2.4 on 2023-10-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0023_remove_task_id_contatti"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratti",
            name="id_commessa",
        ),
        migrations.AddField(
            model_name="contratti",
            name="commesse",
            field=models.ManyToManyField(to="neapolitanmods.commessa"),
        ),
    ]
