# Generated by Django 4.2.4 on 2023-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0024_remove_contratti_id_commessa_contratti_commesse"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratti",
            name="id_attivo",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="contratti",
            name="id_commessa",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="contratti",
            name="id_passivo",
            field=models.BigIntegerField(null=True),
        ),
    ]
