# Generated by Django 4.2.4 on 2023-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0025_contratti_id_attivo_contratti_id_commessa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servizio",
            name="tipologia",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
