# Generated by Django 4.2.4 on 2023-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0028_alter_servizio_documenti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servizio",
            name="documenti",
            field=models.TextField(null=True),
        ),
    ]
