# Generated by Django 4.2.4 on 2023-10-11 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0029_alter_servizio_documenti"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contatti",
            old_name="legale_rappresentante",
            new_name="azienda_di_appartenenza",
        ),
    ]
