# Generated by Django 4.2.4 on 2023-10-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0030_rename_legale_rappresentante_contatti_azienda_di_appartenenza"),
    ]

    operations = [
        migrations.AddField(
            model_name="contatti",
            name="id_azienda",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="contatti",
            name="id_commessa",
            field=models.BigIntegerField(null=True),
        ),
    ]
