# Generated by Django 4.2.4 on 2023-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0031_contatti_id_azienda_contatti_id_commessa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatture",
            name="anno_competenza",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
