# Generated by Django 4.2.4 on 2023-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0032_alter_fatture_anno_competenza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatture",
            name="data_incasso",
        ),
        migrations.AddField(
            model_name="fatture",
            name="id_commessa",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fatture",
            name="id_contratti",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fatture",
            name="stato",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
