# Generated by Django 4.2.4 on 2023-10-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0033_remove_fatture_data_incasso_fatture_id_commessa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatture",
            name="commessa",
        ),
        migrations.AddField(
            model_name="fatture",
            name="commessa",
            field=models.ManyToManyField(to="neapolitanmods.commessa"),
        ),
    ]
