# Generated by Django 4.2.4 on 2023-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0035_remove_fatture_commessa_remove_fatture_id_commessa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="id_utente",
            field=models.BigIntegerField(null=True),
        ),
    ]
