# Generated by Django 4.2.4 on 2023-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0036_task_id_utente"),
    ]

    operations = [
        migrations.AddField(
            model_name="aziende",
            name="id_utente",
            field=models.BigIntegerField(null=True),
        ),
    ]
