# Generated by Django 4.2.4 on 2023-10-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0037_aziende_id_utente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servizio",
            name="referente",
        ),
        migrations.AddField(
            model_name="servizio",
            name="referente",
            field=models.ManyToManyField(to="neapolitanmods.utente"),
        ),
    ]
