# Generated by Django 4.2.4 on 2023-10-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0038_remove_servizio_referente_servizio_referente"),
    ]

    operations = [
        migrations.AddField(
            model_name="servizio",
            name="id_responsabile",
            field=models.BigIntegerField(null=True),
        ),
    ]
