# Generated by Django 4.2.4 on 2023-10-12 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0039_servizio_id_responsabile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servizio",
            old_name="referente",
            new_name="responsabile",
        ),
    ]
