# Generated by Django 4.2.4 on 2023-10-12 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0040_rename_referente_servizio_responsabile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servizio",
            old_name="id_responsabile",
            new_name="id_utente",
        ),
    ]
