# Generated by Django 4.2.4 on 2023-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0041_rename_id_responsabile_servizio_id_utente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aziende",
            name="responsabile",
        ),
        migrations.AddField(
            model_name="aziende",
            name="responsabile",
            field=models.ManyToManyField(to="neapolitanmods.utente"),
        ),
    ]
