# Generated by Django 4.2.4 on 2023-10-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neapolitanmods", "0042_remove_aziende_responsabile_aziende_responsabile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contatti",
            name="azienda_di_appartenenza",
        ),
        migrations.AddField(
            model_name="contatti",
            name="azienda_di_appartenenza",
            field=models.ManyToManyField(to="neapolitanmods.aziende"),
        ),
    ]
