default_context:
  _pegasus_version: 2023.9.2
  author_name: Luca Capozzi
  ci: none
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: heroku_docker
  description: Sistema per la gestione di ingenti quantita di dati per la finanza
    agevolata di WB Servizi Globali
  docker_setup: default
  domain_name: localhost:8000
  email: cinqueinnovation@gmail.com
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: WB Servizi finanza agevolata
  project_slug: wb_servizi_ag
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_keys: y
  use_cloud_media_storage: n
  use_debug_toolbar: y
  use_docker: y
  use_examples: y
  use_impersonation: y
  use_openai: n
  use_sentry: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: n
  use_wagtail: n
