# Generated by Django 4.2.4 on 2023-10-04 10:12

import apps.users.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.FileField(
                blank=True, upload_to="profile-pictures/", validators=[apps.users.helpers.validate_profile_picture]
            ),
        ),
    ]
